version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: "meteor"
    container_name: meeting-room
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:3000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 2089fd8b-b7ba-575b-9f29-bac67123b365
    